version: "3"

networks:
  laravel:
  host:

services:
  nginx:
    image: nginx
    container_name: larquasvite9-nginx
    ports:
    - "8122:80"
    volumes:
      - ./:/var/www/html
      - ./server_dev/nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - laravel
      - host

  php:
    build:
      context: .
      dockerfile: server_dev/Dockerfile
    container_name: larquasvite9-php
    volumes:
      - ./:/var/www/html
    networks:
      - laravel